version: '3.7'

services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: express_db
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbuser@123
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres: